# action.yml
name: 'Corretto on Amazon Linux'
description: 'Runs Corretto on Amazon Linux'
inputs:
  corretto-version: 
    description: 'Corretto version, either 8 or 11'
    required: true
    default: 11
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.corretto-version }}